name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # 00:00 UTC mỗi ngày
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 8
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          COMMIT_MESSAGE: "⏱️ Update WakaTime stats"
